// Export all components
export * from "../backend/auth/middleware";
export * from "../backend/users/routes";
export * from "../backend/courses/routes";
export * from "../backend/videos/routes";
export * from "../backend/auth/routes";
export * from "../backend/playlists/routes";
export * from "../backend/subscriptions/routes";
export * from "../backend/watch-progress/routes";
export * from "../backend/roles/routes";
export * from "../backend/permissions/routes";